services:
  postgres-db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-postgres
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5434:5432"
    volumes:
      - ./docker/init/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: testpass
      ORACLE_DATABASE: users_db
      APP_USER: testuser
      APP_USER_PASSWORD: testpass
    ports:
      - "1521:1521"
    volumes:
      - ./docker/init/oracle/init.sql:/container-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 120s
