app:
  data-sources:
    - name: postgres-db
      strategy: postgres
      table: users
      mapping:
        id: user_id
        username: login
        name: first_name
        surname: last_name
    - name: oracle-db
      strategy: oracle
      table: user_table
      mapping:
        id: ldap_login
        username: ldap_login
        name: name
        surname: surname
